language: node_js
node_js:
- '8'
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- bash travis/commit.sh
deploy:
  provider: npm
  email: nooooru@gmail.com
  api_key:
    secure: ugRVSXPc5Dxx7g7kQI5AoFIAicgTQXDQTLacBZoVY+V4imrOMXbfzDUwUAKcz0yVvrVHOVQRFkFtB+h5eSWaSzgfC660SGCaFkjy3lhiz9K50Nx1V36NrWvRXytQUHJFgaziQIosfHRwTJ5Lgmliy2UtWkL8IZ/Af6zhU46Byfe95tEQ3JPe39XmQn5eQ2Pa00qeaLGl3CU91e3qKvGBcES2sF9GqAyMb5jaTlYiAeN17L67kBFD66XTbZBY4LrEjTdbXKNTsHPsyWqwmgx2nF8ihRCIzOwf46EFrEJLOhFZfYEqDUcGkIE/FuFoEMt8bOYPyKrv4SbqNjPMbWA5Xuiay079rjqYHaHutCXJrwmuWGVLxiyTUKlew4NFKckd52bRKgvQ1GUD4Ks5Y9XR4X2yDg/+1Ye1N5KTfeMwGR+bASjqZWPIiFwLXe10CrN374ttcmuiQJj44XObHvSlPu27DhgLXnvhv5JxgQSqy1JX862/ACDa9Ahufsa+pn9baGN0vzpqrGIk1yvErGfWBZKWMiZX/3MNN2sQzkyyvhLk5VN3ikIgTB5JQHtSZC3fKqifN0aIG4i0j7z4qiJQWewo+p4ZxdRAGnO6AGyqf1pYwXS326gO/JOG1q+k4zBn8i8jNdo5DcjHG4T58P0pJa89qHYBkwafISeUPbtHV2I=
  on:
    repo: noru/vue-resource-mock
env:
  global:
    secure: uPzMR8FFvwoO9NNBACshbopAaNTAYRBocmIQzNHLuaSTInpJl4NUtQLO3SjEgW64dyE/gVk6+bJYRaDxlFo81gLDJJUIhtuoEUxP5AEbhJZGM91BYm3HZaOPq7gCrOiY0qSVj6TOEIJzpB1hGGCyPq62wy7q5J9Hp+tEyl0iXwva538CUaeB8z+090d3mKdJVFMt1ETph5fgvUMJQVf9uioaVC57f2Em/Yhh1ZxcQS9BLCM3T4DTXmlBg5gbNShjwDjOidLxPMTz7Gx5KprS5wYOxsGqdgVtA2miY/jezNPOg/A17b0fEqdWeIvDzmKCwi9mngNa2McYRR41HGZQi63fkFOjG70gga7a/JUhZNMEkS53k8ifUU5snODULW4cqsYut/vSqhRtaE/wREScOXIe2PfEd5TR5BGrlh1U1SMz4fty9z6lQ3iOuNqiMMQ556lnCmU6u4NVI4Z2saZ3/pNa1jqIzmiGvSuv2X4hAbh4HuPp4QcRkexnoqJqoBrwE9GUsc8uhShwV5dii2v+LVW/jKCiDdkJynfyeIf2ernsoQEW8rbQffgLPgVIhcM/TH+5P5Ef+TrT97G2P1m1zw4/U1cURiWZtyDQqkeVmn79YaAiXX7PWr0F/hhp4xwh0HPAlzcA1lVdGp6zK/ezlh0hipkvMG4sOUfEwfBESZQ=
